
version: '2.1'

services:
    users-db:
        container_name: users-db
        build: ./plato/db
        ports:
            - 5435:5432     # expose ports - HOST:CONTAINER
        environment:
            - POSTGRES-USER=postgres
            - POSTGRES-PASSWORD=postgres
        healthcheck:
            test: exit 0

    users-service:
        container_name: users-service
        build: ./
        volumes:
            - '.:/usr/src/app'
        expose:
            - '5000'
        environment:
            - APP_SETTINGS=plato.config.DevelopmentConfig
            - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
            - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
        depends_on:
            users-db:
                condition: service_healthy
        links:
            - users-db
        command: gunicorn -b 0.0.0.0:5000 manage:app

    nginx:
        container_name: nginx
        build: ./nginx/
        restart: always
        ports:
          - 80:80
        depends_on:
          users-service:
            condition: service_started
        links:
          - users-service
